# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bowlingdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret2
    ports: 
        - 3306:3306
